### ISSUE TITLE
Exception in HostObject::get for prop 'RNCGeolocation': java.lang.NullPointerException: Null context is not permitted., js engine: hermes

### ISSUE THREAD

**Issue by petrlz63** [michalchudziak/react-native-geolocation#206]
## Environment
production

## Platforms
Android

## Versions
- Android: 8-13
- react-native-geolocation: 3.x
- react-native: 0.69.5
- react: 18

## Description
After update react-native-geolocation to 3 (tried all 3.x versions) we are getting this error on multiple android devices:
Error: Exception in HostObject::get for prop 'RNCGeolocation': java.lang.NullPointerException: Null context is not permitted., js engine: hermes

## Reproducible Demo
Sadly we can't reproduce it on our own test devices :/

**Comment by michalchudziak** [comment]
Could you provide me with more detailed environment info, or ideally with a minimal repro project?

**Comment by jplandry908** [comment]
I'm having the same issue and am unable to figure out the root cause. I'm on react-native 0.70.2. All I did was upgrade from react-native-geolocation v2.1.0 to v3 (tried 3.0.0, 3.0.1, and 3.0.2) and seeing this crash.  It appears to only show up in Android Release mode. I'm not seeing any issues on iOS (debug or release) or Android (debug). It was not noticed until deployed for distribution, but I am also able to detect it in the emulator if I change it to release.

No other code changes were made and if I download back to v2.1.0 the error goes away.

Fatal Exception: com.facebook.react.common.JavascriptException
Error: Exception in HostObject::get for prop 'RNCGeolocation': java.lang.NullPointerException: Null context is not permitted., js engine: hermes, stack: anonymous@1:712046 loadModuleImplementation@1:71965 guardedLoadModule@1:71513 metroRequire@1:71141 anonymous@1:710866 loadModuleImplementation@1:71965 guardedLoadModule@1:71513 metroRequire@1:71141 anonymous@1:709995 loadModuleImplementation@1:71965 guardedLoadModule@1:71513 metroRequire@1:71141 anonymous@1:705118 loadModuleImplementation@1:71965 guardedLoadModule@1:71513 metroRequire@1:71141 anonymous@1:594601 loadModuleImplementation@1:71965 guardedLoadModule@1:71513 metroRequire@1:71141 anonymous@1:592109 loadModuleImplementation@1:71965 guardedLoadModule@1:71513 metroRequire@1:71141 anonymous@1:78353 loadModuleImplementation@1:71965 guardedLoadModule@1:71470 metroRequire@1:71141 global@1:70716

**Comment by jplandry908** [comment]
Some additional info ... 

The crash happens before your react-native code is able to be processed (less than a second of running). I also commented out references to this module within the code (even the import statement) and still able to reproduce the crash.

**Comment by jplandry908** [comment]
HI @michalchudziak. This appears to be related to Hermes. I took a look at your example and it appears Hermes is set to false and the new architecture is set to true. My project has Hermes set to true and the new architecture set to false. I disabled hermes and the app was able to launch successfully.

**Comment by michalchudziak** [comment]
> HI @michalchudziak. This appears to be caused when Hermes is enabled. I took a look at your example and it Hermes is set to false and the new architecture is set to true. My project has Hermes set to true and the new architecture set to false. I disabled Hermes and the app was able to launch successfully.

That's a good lead, I will test it out today. Thanks

**Comment by michalchudziak** [comment]
I just tried out the example app with Hermes enabled and I can't reproduce the issue. Could you provide me with a minimal repro project? I will be happy to fix the issue as soon as I'm able to reproduce it.

**Comment by michalchudziak** [comment]
Also, more info about the affected devices/build flavor, etc will be helpful.

**Comment by jplandry908** [comment]
Let me see if I can figure out what is different between my solution and your example. I'll do some more troubleshooting and get back to you.

**Comment by jplandry908** [comment]
@michalchudziak. I was able to reproduce this issue with a clean install by following the following steps.

**1. Create new react-native app**
  react-native init test --version 0.70.2
  
**2. Install geolocation module within new app**
npm install @react-native-community/geolocation

**3. Add geolocation import to default 'App.js' file**
import Geolocation from '@react-native-community/geolocation';

**4. Run using Build Variant 'release' (not debug)**

Every time you attempt to launch the app, it crashes every time.

**Comment by michalchudziak** [comment]
@jplandry908 Can you tell me which device you use? I followed these steps on the Pixel emulator & physical Samsung S10 and everything works well. Maybe it's specific to some group of devices?

**Comment by jplandry908** [comment]
Hi @michalchudziak. How strange, I was able to reproduce the crash on every emulator I tried. Pixel 5 (API 31), Pixel 4 (API 29), & Pixel 3 (API 30) are some examples. Also, when I only update this module on my production app, it works fine in iOS and Android DEBUG locally but if I test on the release variant it fails. I detected this (since I rarely change my local variant to release) when I pushed it to Google Play store and it failed all 10 of their random tests using random devices. Let me package up my test project for you.

@petrlz63 - Yo you have any other information? It sounds like you are experiencing the same issue when trying to upgrade your app.

**Comment by michalchudziak** [comment]
@jplandry908 Thank you a lot, I'm able to reproduce and fix the issue. I'll ship the new version soon :)

**Comment by michalchudziak** [comment]
Fixed in 3.0.3 release

**Comment by jplandry908** [comment]
Thanks @michalchudziak. I can confirm that the issue appears to have been fixed in the v3.0.3 release. I appreciate your support!
